baseURL: https://hallcdcs550.netlify.app/
title: Charlie's test blog for DCS 550
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: John Doe
  description: This is my description of my site.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/hallc-14
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]